#ifndef CKBEHAVIORPROTOTYPE_H
#define CKBEHAVIORPROTOTYPE_H

#include "CKObject.h"
#include "CKObjectDeclaration.h"

#define STRINGDUPLICATION

#ifdef STRINGDUPLICATION
#define MAKESTRING(a) CKStrdup(a)
#define DELETESTRING(a) CKDeletePointer(a)
#else
#define MAKESTRING(a) a
#define DELETESTRING(a)
#endif

struct CKPARAMETER_DESC
{
    char *Name; // Parameter Name
    CKGUID Guid;   // Guid identifying the type
    int Type;      // In, Out or local
    char *DefaultValueString;
    CKBYTE *DefaultValue;
    int DefaultValueSize;
    int Owner;

    DLL_EXPORT CKPARAMETER_DESC();
    DLL_EXPORT CKPARAMETER_DESC(const CKPARAMETER_DESC &d);
    DLL_EXPORT ~CKPARAMETER_DESC();
    DLL_EXPORT CKPARAMETER_DESC &operator=(const CKPARAMETER_DESC &d);
};

struct CKBEHAVIORIO_DESC
{
    char *Name; // Name of this IO
    CKDWORD Flags; // Flags	In/Out/active etc

    // Ctor
    DLL_EXPORT CKBEHAVIORIO_DESC();
    // Dtor
    DLL_EXPORT ~CKBEHAVIORIO_DESC();
};

/*************************************************
Summary: Class describing the prototype of a behavior

Remarks:
    + A behavior prototype is a kind of model for behaviors. Behavior prototypes describe the behavior's
    internal structure and relationships with other objects.
    Prototypes are usually created in external dlls, but may be created in memory.
    For more information on creation of behavior dlls take a look to the behavior samples joined
    in this SDK.

    + Prototypes are usually defined in a Dll. This prototype is created the first time it is needed,
    that is either when a behavior in Virtools is drag-n-dropped onto an object, or when a behavior is loaded
    that is derived from the prototype. In this case, the main dll entry point CKDLL_CREATEPROTOFUNCTION
    will create the behavior prototype, that will be used to create the behavior using the CKBehavior::InitFromPrototype method.
    A prototype may use other prototypes, as sub-prototypes, thus generating sub-behaviors.

    + Each prototype that should be standalone, either in a dll, or in a standalone file, should have a GUID.
    A guid can be generated by using the CKGetSecureGuid function. If the prototype is created in a dll, the GUID is provided
    using the object declaration. If the prototype is created in memory, the GUID can be set using the CKBehaviorPrototype::SetGuid method.

    + A name can be provided for various parts of the behavior. This name is not used for indexing
    and does not have to be unique. It is provided as a convenience for display and debugging purposes.

    + A CKBehaviorPrototype is created with CreateCKBehaviorPrototype.


See also: CreateCKBehaviorPrototype,CKBehavior
*************************************************/
class CKBehaviorPrototype
{
    friend class CKBehavior;

public:
    //---------------------------------------------------------------------
    // Inputs, outputs, out parameters, in parameters, local parameters and settings (special local parameters)
    virtual int DeclareInput(CKSTRING name);
    virtual int DeclareOutput(CKSTRING name);

    virtual int DeclareInParameter(CKSTRING name, CKGUID guid_type, CKSTRING defaultval = NULL);
    virtual int DeclareInParameter(CKSTRING name, CKGUID guid_type, void *defaultval, int valsize);

    virtual int DeclareOutParameter(CKSTRING name, CKGUID guid_type, CKSTRING defaultval = NULL);
    virtual int DeclareOutParameter(CKSTRING name, CKGUID guid_type, void *defaultval, int valsize);

    DLL_EXPORT int DeclareLocalParameter(CKSTRING name, CKGUID guid_type, CKSTRING defaultval = NULL);
    DLL_EXPORT int DeclareLocalParameter(CKSTRING name, CKGUID guid_type, void *defaultval, int valsize);

    DLL_EXPORT int DeclareSetting(CKSTRING name, CKGUID guid_type, CKSTRING defaultval = NULL);
    DLL_EXPORT int DeclareSetting(CKSTRING name, CKGUID guid_type, void *defaultval, int valsize);

    //--------------------------------------------------------------------
    // Behavior Description functions
    DLL_EXPORT void SetGuid(CKGUID guid);
    DLL_EXPORT CKGUID GetGuid();

    DLL_EXPORT void SetFlags(CK_BEHAVIORPROTOTYPE_FLAGS flags);
    DLL_EXPORT CK_BEHAVIORPROTOTYPE_FLAGS GetFlags();

    DLL_EXPORT void SetApplyToClassID(CK_CLASSID cid);
    DLL_EXPORT CK_CLASSID GetApplyToClassID();

    DLL_EXPORT void SetFunction(CKBEHAVIORFCT fct);
    DLL_EXPORT CKBEHAVIORFCT GetFunction();

    DLL_EXPORT void SetBehaviorCallbackFct(CKBEHAVIORCALLBACKFCT fct, CKDWORD CallbackMask = CKCB_BEHAVIORALL, void *param = NULL);
    DLL_EXPORT CKBEHAVIORCALLBACKFCT GetBehaviorCallbackFct();

    DLL_EXPORT void SetBehaviorFlags(CK_BEHAVIOR_FLAGS flags);
    DLL_EXPORT CK_BEHAVIOR_FLAGS GetBehaviorFlags();

    /*******************************************
    Summary: Returns the name of this prototype
    Return Value:
        Prototype name.
    See Also: GetGuid
    ********************************************/
    DLL_EXPORT CKSTRING GetName() { return m_Name.Str(); }

    //-------------------------------------------------------------------
    // Internal functions

    //---------------------------------------------------------------------
    // Info Functions {Secret}
    DLL_EXPORT int GetInputCount() { return m_InIOCount; }
    DLL_EXPORT int GetOutputCount() { return m_OutIOCount; }
    DLL_EXPORT int GetInParameterCount() { return m_InParameterCount; }
    DLL_EXPORT int GetOutParameterCount() { return m_OutParameterCount; }
    DLL_EXPORT int GetLocalParameterCount() { return m_LocalParameterCount; }
    DLL_EXPORT CKBEHAVIORIO_DESC **GetInIOList() { return m_InIOList; }
    DLL_EXPORT CKBEHAVIORIO_DESC **GetOutIOList() { return m_OutIOList; }
    DLL_EXPORT CKPARAMETER_DESC **GetInParameterList() { return m_InParameterList; }
    DLL_EXPORT CKPARAMETER_DESC **GetOutParameterList() { return m_OutParameterList; }
    DLL_EXPORT CKPARAMETER_DESC **GetLocalParameterList() { return m_LocalParameterList; }

    // Typo retained for compatibility
    DLL_EXPORT CKObjectDeclaration *GetSoureObjectDeclaration();

    DLL_EXPORT int GetInIOIndex(CKSTRING name);
    DLL_EXPORT int GetOutIOIndex(CKSTRING name);
    DLL_EXPORT int GetInParamIndex(CKSTRING name);
    DLL_EXPORT int GetOutParamIndex(CKSTRING name);
    DLL_EXPORT int GetLocalParamIndex(CKSTRING name);

    DLL_EXPORT CKSTRING GetInIOName(int);
    DLL_EXPORT CKSTRING GetOutIOName(int);
    DLL_EXPORT CKSTRING GetInParamName(int);
    DLL_EXPORT CKSTRING GetOutParamName(int);
    DLL_EXPORT CKSTRING GetLocalParamName(int);

    void SetSourceObjectDeclaration(CKObjectDeclaration *decl) { m_SourceObjectDeclaration = decl; }

    virtual ~CKBehaviorPrototype();
    CKBehaviorPrototype(CKSTRING Name);

    virtual CKBOOL IsRunTime() { return FALSE; }

private:
    CKGUID m_Guid;
    CK_BEHAVIORPROTOTYPE_FLAGS m_bFlags;
    CK_BEHAVIOR_FLAGS m_BehaviorFlags;
    CK_CLASSID m_ApplyTo;
    CKBEHAVIORFCT m_FctPtr;
    CKBEHAVIORCALLBACKFCT m_CallbackFctPtr;
    CKDWORD m_CallBackMask;

    int m_InIOCount;
    int m_OutIOCount;
    int m_InParameterCount;
    int m_LocalParameterCount;
    int m_OutParameterCount;
    CKBEHAVIORIO_DESC **m_InIOList;
    CKBEHAVIORIO_DESC **m_OutIOList;
    CKPARAMETER_DESC **m_InParameterList;
    CKPARAMETER_DESC **m_OutParameterList;
    CKPARAMETER_DESC **m_LocalParameterList;
    CK_BEHAVIOR_TYPE m_BehaviorType;
    void *m_CallBackParam;
    CKObjectDeclaration *m_SourceObjectDeclaration;

    XString m_Name;
};

#endif // CKBEHAVIORPROTOTYPE_H
